const EXAMS = {
  "화작": {
    questions: [
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" }
    ]
  },

  "미적분": {
    questions: [
     { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "short" },
      { answer: "3", score: 4, type: "short" },
      { answer: "2", score: 4, type: "short" },
      { answer: "4", score: 4, type: "short" },
      { answer: "2", score: 4, type: "short" },
      { answer: "1", score: 4, type: "short" },
      { answer: "3", score: 4, type: "short" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "short" },
      { answer: "2", score: 4, type: "short" }
      
    ]
  },

 "확통": {
    questions: [
     { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "short" },
      { answer: "3", score: 4, type: "short" },
      { answer: "2", score: 4, type: "short" },
      { answer: "4", score: 4, type: "short" },
      { answer: "2", score: 4, type: "short" },
      { answer: "1", score: 4, type: "short" },
      { answer: "3", score: 4, type: "short" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "1", score: 4, type: "choice" },
      { answer: "3", score: 4, type: "choice" },
      { answer: "2", score: 4, type: "choice" },
      { answer: "4", score: 4, type: "short" },
      { answer: "2", score: 4, type: "short" }
      
    ]
  },
